nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:8000/']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['*']
        max_age: 3600
    paths:
        '^/': ~